apiVersion: batch/v1
kind: Job
metadata:
  name: storage-tester-job
spec:
  template:
    annotations:
      gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: {{ .Values.job.bucketName }}
              mountOptions: "implicit-dirs"
      containers:
      - name: storage-tester
        image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        env:
          - name: ACTION_DIRECTORY
            value: {{ .Values.job.actionDirectory }}
        volumeMounts:
          - name: gcs-fuse-csi-ephemeral
            mountPath: {{ .Values.job.actionDirectory }}
            readOnly: false
      restartPolicy: Never
  backoffLimit: 4
