apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-fuse-csi-job-example
  namespace: NAMESPACE
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: test-storage-chart
      containers:
      - name: storage-tester
        image: gat786/gcs-fuse-test:latest
        env:
        - name: ACTION_DIRECTORY
          value: /data
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
      volumes:
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: test-storage-mounting
      restartPolicy: Never
  backoffLimit: 1
